// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/doctor-dashboard/Alerts.tsx": () => import("../components/mockups/doctor-dashboard/Alerts.tsx"),
  "./components/mockups/doctor-dashboard/Patients.tsx": () => import("../components/mockups/doctor-dashboard/Patients.tsx"),
  "./components/mockups/doctor-dashboard/Profile.tsx": () => import("../components/mockups/doctor-dashboard/Profile.tsx"),
  "./components/mockups/doctor-dashboard/Today.tsx": () => import("../components/mockups/doctor-dashboard/Today.tsx"),
  "./components/mockups/doctor-dashboard/Tools.tsx": () => import("../components/mockups/doctor-dashboard/Tools.tsx")
};
